### PR TITLE
Add field lines survival probability as detector argument

### PR DESCRIPTION
**Pull request by ramirezdiego**
**What is the problem / what does the code in this PR do**

Replicating the exact methods already available for the position-dependent efield handling, the field lines survival probability is added as a detector input (either the path to a map or a constant value ranging from 0 to 1).

**Testing/comments**

I tested the correct propagation for a constant value by setting (`[TPC]`) `survival_probability=0.5` in the detector configuration files and comparing the output with that for the default (`survival_probability=1`) case. It would be good to have a map by @ftoschi for testing with the same format as the efield maps, but there is no reason for it not to work, since the `ElectricFieldHandler` isn't changed.

For some cases, e.g. below cathode interactions, `survival_probability=0` and `create_S2=False` are redundant. I guess we want to keep both for the moment? @WenzDaniel?

### CODE REVIEW

**Comment by WenzDaniel** [comment]
> For some cases, e.g. below cathode interactions, survival_probability=0 and create_S2=False are redundant. I guess we want to keep both for the moment? 
Would not it be also redundant in other volumes ? If survival_probability>0 -> create_S2=True? Not sure.

**Comment by ramirezdiego** [comment]
> 
> 
> > For some cases, e.g. below cathode interactions, survival_probability=0 and create_S2=False are redundant. I guess we want to keep both for the moment?
> 
> Would not it be also redundant in other volumes ? If survival_probability>0 -> create_S2=True? Not sure.

Exactly, so maybe we can delete this option?

**Comment by ramirezdiego** [comment]
The ongoing discussion is whether this effect should be included together with other drif field effects and queried from wfsim, rather than here. Opinions?

**Comment by WenzDaniel** [comment]
As Henning correctly pointed out, this is a detector effect and given our current organization of the Full-Chain simulation I would implement these changes in WFSim.

**Comment by ramirezdiego** [comment]
That's why I wanted to trigger this discussion. Both options make sense to me, so maybe we need some more people sharing their thoughts.

Indeed this is a detector effect, but the same happens with the efield map that we use in here. At the end, epix provides the output in terms of number of electrons that we want to propagate in WFsim, and these that will end up in the wall don't belong to that category (same as we cut the electrons below cathode before producing the instructions). Another argument to keep it here is that currently WFsim does not use field maps, therefore we would need to code in there some routines that are already available in epix.

If you are convinced that this should go into WFsim, then we must duplicate the map reading in there and combine it with the drift velocity and diffusion constant information along the path, where something like `drift_velocity = nan` ([see this map](https://xe1t-wiki.lngs.infn.it/lib/exe/fetch.php?media=xenon:xenonnt:ftoschi:drift_speed_map.png)) would mean that electrons in that bin shouldn't be computed.

**Comment by ramirezdiego** [comment]
Field lines survival probability will be handled in WFSim: https://github.com/XENONnT/WFSim/pull/130

**Pull request closed without merging**
