### PR TITLE
Add NR cut to file loader

### PR DESCRIPTION
**Pull request by PavelKavrigin**
Simple implementation of NR selections from ROOT files using a modified cut string. An additional parameter in the configuration ('nr_only') is used to turn on/off this cut. This PR can be used as a basis for other cuts or a modification of this cut.

### CODE REVIEW

**Comment by PavelKavrigin** [comment]
Here's a basic test using 20 files with AmBe simulations. These are 'e_dep' histograms, with NR-only selection via cut string and without the cut. The output of this branch is compared to the master branch of epix. NR selection in the master branch was done by selecting only 'recoil==0' rows from the output.

2021-12-22_EpixNRCutTrue
2021-12-22_EpixNRCutFalse

**Comment by zhut19** [comment]
Hi @PavelKavrigin @ramirezdiego , it is better to keep the non-neutron / ion energy deposition in the same event, no?
So the nr selection cannot apply at the root to array level, but a bit trickier after that line.
Here is some example code I am trying:
```mask = ((interactions['type'] == "neutron") & (interactions['edproc'] == "hadElastic")) | (interactions['edproc'] == "ionIoni")```
```interactions = interactions[ak.num(interactions[mask])['x'] > 0]```

**Comment by ramirezdiego** [comment]
@shenyangshi Do you think you can jump on this, following the syntax by Pavel and the above suggestion by @zhut19?

**Comment by shenyangshi** [comment]
Hi @ramirezdiego, the NR selection is implemented. I select events with summed ER components smaller than 32kev and having NR components larger than 0kev. Here is the graph showing the NR components considering the ER effect or not.

image

**Comment by WenzDaniel** [comment]
Just for the record: This means that we are removing events with an inelastic component a 40 keV and 100 keV.  This might be important for any TPC based neutron-veto.

**Comment by PavelKavrigin** [comment]
Is it safe to ignore the timing and the location of the energy depositions? There could be cases where NR and ER do not occur close to each other. We will throw away all of these events based on the total energy.

**Comment by shenyangshi** [comment]
Maybe yes, as NR and ER particles are all nearly to the speed of light, so both NR and ER will contribute to the S1, but for S2 if the distance is far maybe one of them won't be in the same event window, but this kind of event won't be in the neutron band anyway.

**Comment by WenzDaniel** [comment]
Based on how we build events the S2 should be within the event as long as the second interaction happens in the sensitive volume.

**Comment by WenzDaniel** [comment]
In any case a suggestion. I think it is worthwhile to store a second epix file containing all "rejected events".

**Comment by ramirezdiego** [comment]
> Just for the record: This means that we are removing events with an inelastic component a 40 keV and 100 keV. This might be important for any TPC based neutron-veto.

@WenzDaniel Not sure I get your comment. This cut should only be applied when we want to estimate the pure NR SS, so disabled by default.

**Comment by ramirezdiego** [comment]
@shenyangshi  @PavelKavrigin If this is not adding a significan delay to the code, I would suggest that we always store the `e_dep_er` and `e_dep_nr` branches per event, and use the `nr_cut` flag to simply select events according to them (this can also help @WenzDaniel with his current checks, maybe?).

On the other side, if the output file can't be modified now (because this would require doing the same with WFSim), let's just leave these branches floating and fix that in future commits.

**Comment by shenyangshi** [comment]
No, it just comes to me that the ER energy in NR events is well above the NR energy scale, so selecting 10kev or 32kev wouldn't make a difference to the results. The upper bound for Ed_nr*Lindhard factor is around 32kev, so I selected this value.

**Comment by shenyangshi** [comment]
Sure, it's done, sorry I didn't notice this file before.

**Review by ramirezdiego — APPROVED** [review]

**Pull request merged**
