### PR TITLE
Update s2 separation

### PR DESCRIPTION
**Pull request by jarongrigat**
- Add new S2 macro clustering algorithm
-  S1 is now sum of all 1-type depositions (again? was done like this by Giovanni but somehow didn't survive in current branch)
-  Add epix option `load_from_file` to load epix instructions .npy directly 
- some OCD typo and formatting corrections.

This PR looks somewhat messy but if we merge `master` into `fast_simulator` before it should be better.

### CODE REVIEW

**Comment by jarongrigat** [comment]
Yes for sure. I will write up a note. probably done on Monday.

**Comment by PavelKavrigin** [comment]
```
---> 60 self.tree = pickle.load(open('/dali/lgrandi/jgrigat/s2_separation/tree_v2_unoptimised', 'rb+'))
     62 Helpers.macro_cluster_events(self.tree, self.instructions_epix, self.config)
     63 self.instructions_epix = self.instructions_epix[self.instructions_epix['amp'] != -1]

FileNotFoundError: [Errno 2] No such file or directory: '/dali/lgrandi/jgrigat/s2_separation/tree_v2_unoptimised'
```

@jarongrigat - Please do not link DALI here :)). We should pass the path to the tree either as an argument, or add this file to some dedicated directory for FastSim data files.

**Comment by ramirezdiego** [comment]
Hey jaron, do you think you could take care of resolving the conflicts of the fast_simulator branch?
> This PR looks somewhat messy but if we merge master into fast_simulator before it should be better.

**Comment by jarongrigat** [comment]
Yes I can do that. Also trying to merge everything into a working fastsim version.

**Pull request closed without merging**
