### PR TITLE
Fast simulator dev

### PR DESCRIPTION
**Pull request by petergaemers**
This pull request:

- Adds the first version of the Fast-Simulator a la nSort to epix

Usage: There is a notebook, though you'll need to change some of the paths

### CODE REVIEW

**Comment by ramirezdiego** [comment]
@petergaemers thanks for this push! I expect to have time to look at it next week. In the meantime, it would be good if you add some extra information. I know this is a working skeleton that needs to be polished, but can you list...?
- The fundamental effective corrections you apply to data, and what you consider is missing for future commits.
- Which functions you fetch directly from WFSim.
- How do you plan to fetch the detector parameters, such as elifetime, etc.

**Comment by petergaemers** [comment]
- I do (in order):
1. Gaussian smearing of positions
2. Make s1s with wfsim light yield & average spe area distribution
3. Make s2s, first drift(+elife loss) then scintillate with sc_gain
4. Corrections according to https://github.com/XENONnT/straxen/blob/e2e6202e287575607145204f2e4823f908521e6b/straxen/plugins/event_processing.py#L432 

As far as I know this is everything. So I need someone to check if this is actually correct
- Light and charge yield functions are copies from wfsim, though Pavel removed the direct using of wfsim (don't know if there is a particular reason)
- Detector parameters are taken from the fax configuration

**Comment by ramirezdiego** [comment]
>     * Light and charge yield functions are copies from wfsim, though Pavel removed the direct using of wfsim (don't know if there is a particular reason)

What do you mean here? That now there's some copy-paste?

**Comment by PavelKavrigin** [comment]
> Light and charge yield functions are copies from wfsim, though Pavel removed the direct using of wfsim (don't know if there is a particular reason)

I had some problem with loading the latest version of wfsim in my environment back then, that's why I just copied the code eventually. There's no reason to keep it this way now.

**Comment by petergaemers** [comment]
Oke I removed them

**Pull request closed without merging**
