### PR TITLE
Update giovanni

### PR DESCRIPTION
**Pull request by GiovanniVolta**
Hi All,

I think it is time to review my work for FastSim. I open a draft of this PR only to get attention. For sure, there is something to adjust, in particular regarding how to handle the config file.

We should ask someone to try the code and check if there is something to change/modify/adjust.

Any idea? I think someone from high energy could do this. I can provide some notebooks.

Cheers,

Giovanni

### CODE REVIEW

**Comment by ramirezdiego** [comment]
Hey @GiovanniVolta, I am seeing the notifications from @PavelKavrigin's fixes and I wonder why your branch seems to be behind the last one he worked on. Correct me if I am wrong.

**Comment by PavelKavrigin** [comment]
@GiovanniVolta @ramirezdiego - I think we should merge this update into **fast_simulator** and do all further updates in **fast_simulator** branch. The things I've changed so far:

- merged the master branch;
- added Jaron's BDT file for S2 merging algorithm as one of the configuration files;
- added the type of the S2 merging algorithm as an input parameter (naive/nSort/BDT);
- commented out the second call to "Helpers.macro_cluster_events": [here](https://github.com/XENONnT/epix/blob/update_giovanni/epix/simulator/fast_simulator.py#L57-L59)
- added a new example/test notebook.

**Comment by ramirezdiego** [comment]
Sounds good, thanks a lot. But why do we have conflicts if this branch was updated on top of `fast_simulator`? I'll resolve them and merge if you think it looks good.

**Comment by PavelKavrigin** [comment]
I am not sure why do we have these conflicts. I guess I made some changes to the **fats_simulator** branch while Giovanni was working on **update_giovanni**. But we can use Giovanni's version to resolve the conflicts.

**Comment by ramirezdiego** [comment]
Could someone have a look at `GenerateEvents.py` and confirm I didn't overwrite anything important?

**Pull request merged**
