### PR TITLE
Update fast_simulator.py

### PR DESCRIPTION
**Pull request by petergaemers**
Fix small error in setting the start and end times of the chunk

### CODE REVIEW

**Comment by GiovanniVolta** [comment]
Hey Peter,
as I wrote in slack I have tried your solution, but it doesn't solve the `Attempt to create chunk [...] with non-integer start times` error.
Furthermore, I have to slight change your code because I had `No loop matching the specified signature and casting was found for ufunc` error.
Here below the code:
```
start=int(np.floor(simulated_data_nveto['time'][0])), 
end=np.ceil(np.max(simulated_data_nveto['endtime']))
```

**Comment by petergaemers** [comment]
From looking at the numpy documentation, I thought I could use `dtype=np.int` to return an integer. Turns out I was wrong. Your solution returns a float, so strax complains. Now it should work

**Comment by GiovanniVolta** [comment]
It does! I am testing it one more time

**Review by GiovanniVolta — APPROVED** [review]
Tested and it works both Pavel notebook and mine! Thank you, Peter

**Review by PavelKavrigin — APPROVED** [review]

**Pull request merged**
